name: Scheduled Tests
on:
  schedule:
    # Run tests daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scheduled-tests:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/ 